In [1]:
"""Ten NumPy exercises based on the W3Resource NumPy practice topics.

Run with: python exercises.py
"""

import numpy as np


def heading(number, title):
    print(f"\n{'=' * 12} Exercise {number}: {title} {'=' * 12}")


def exercise_1():
    """Print the installed NumPy version."""
    heading(1, "NumPy version")
    print(np.__version__)


def exercise_2():
    """Convert a list of numeric values to a one-dimensional array."""
    heading(2, "List to 1D array")
    values = [12.23, 13.32, 100, 36.32]
    print(np.array(values))


def exercise_3():
    """Create a 3x3 matrix with values from 2 through 10."""
    heading(3, "3x3 matrix")
    print(np.arange(2, 11).reshape(3, 3))


def exercise_4():
    """Create a null vector of size 10, then make its fifth value 1."""
    heading(4, "Null vector")
    vector = np.zeros(10, dtype=int)
    vector[4] = 1
    print(vector)


def exercise_5():
    """Create values evenly spaced between 0 and 1."""
    heading(5, "Evenly spaced values")
    print(np.linspace(0, 1, 11))


def exercise_6():
    """Reverse an array without using a loop."""
    heading(6, "Reverse an array")
    values = np.arange(10, 22)
    print(values[::-1])


def exercise_7():
    """Find the maximum and minimum values of a flattened array."""
    heading(7, "Maximum and minimum")
    values = np.array([[0, 1], [2, 3]])
    print("Maximum:", np.max(values))
    print("Minimum:", np.min(values))


def exercise_8():
    """Perform element-wise arithmetic on two arrays."""
    heading(8, "Element-wise arithmetic")
    first = np.array([1, 2, 3, 4])
    second = np.array([5, 6, 7, 8])
    print("Addition:", first + second)
    print("Subtraction:", first - second)
    print("Multiplication:", first * second)
    print("Division:", first / second)


def exercise_9():
    """Sort an array along different axes and after flattening it."""
    heading(9, "Sort along axes")
    values = np.array([[10, 40], [30, 20]])
    print("First axis:\n", np.sort(values, axis=0))
    print("Last axis:\n", np.sort(values, axis=1))
    print("Flattened:", np.sort(values, axis=None))


def exercise_10():
    """Compute the square root of every value in a two-dimensional array."""
    heading(10, "Square root ufunc")
    values = np.array([[1, 4, 9], [16, 25, 36]])
    print(np.sqrt(values))


if __name__ == "__main__":
    for exercise in (
        exercise_1, exercise_2, exercise_3, exercise_4, exercise_5,
        exercise_6, exercise_7, exercise_8, exercise_9, exercise_10,
    ):
        exercise()



============ Exercise 1: NumPy version ============
2.3.2

============ Exercise 2: List to 1D array ============
[ 12.23  13.32 100.    36.32]

============ Exercise 3: 3x3 matrix ============
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

============ Exercise 4: Null vector ============
[0 0 0 0 1 0 0 0 0 0]

============ Exercise 5: Evenly spaced values ============
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

============ Exercise 6: Reverse an array ============
[21 20 19 18 17 16 15 14 13 12 11 10]

============ Exercise 7: Maximum and minimum ============
Maximum: 3
Minimum: 0

============ Exercise 8: Element-wise arithmetic ============
Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]

============ Exercise 9: Sort along axes ============
First axis:
 [[10 20]
 [30 40]]
Last axis:
 [[10 40]
 [20 30]]
Flattened: [10 20 30 40]

============ Exercise 10: Square root ufunc ============
[[1. 2. 3.]
 