In [1]:
import numpy

In [6]:
import numpy as np


In [7]:
a=np.array([1,2,3,4,5])

In [8]:
print(a.shape)
print(a.dtype)

(5,)
int64


In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
arr=np.array([10,20,30,40,50])
arr[1:4]

array([20, 30, 40])

In [14]:
arr[0]


np.int64(10)

In [15]:
arr[-1]

np.int64(50)

In [3]:
import numpy as np

In [4]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
m[1,1]

np.int64(5)

In [5]:
m[:,1]

array([2, 5, 8])

In [10]:
a=4
b=2

In [11]:
a+b*a*b*a/b*a**2*np.sqrt(a)

np.float64(1028.0)

In [12]:
a=2
b=3
a+b*a/b**2*np.sqrt(a)


np.float64(2.9428090415820636)

In [13]:
marks=np.array([50,60,70])
marks+5

array([55, 65, 75])

In [17]:
A=np.array([[1,2],[2,3]])
B=np.eye(2)
A@B

array([[1., 2.],
       [2., 3.]])

In [20]:
A@(B@A).T

array([[ 5.,  8.],
       [ 8., 13.]])

In [21]:
A@B.T

array([[1., 2.],
       [2., 3.]])

In [23]:
arr=np.array([1,2,3,4,5])


In [24]:
np.mean(arr)

np.float64(3.0)

In [25]:
np.median(arr)

np.float64(3.0)

In [26]:
np.std(arr)

np.float64(1.4142135623730951)

In [27]:
np.var(arr)

np.float64(2.0)